version: "2"
services:
  staged:
    image: us.gcr.io/smn-core-staging/service.view-store.dashboard:latest
    container_name: staged
    ports:
      - "50051:50051"
    environment:
      - PORT
      - NODE_ENV
      - NETWORK
      - SERVICE
      - DOMAIN
      - ID
      - GCP_PROJECT
      - GCP_REGION
      - GCP_SECRET_BUCKET
      - GCP_KMS_SECRET_BUCKET_KEY_LOCATION
      - GCP_KMS_SECRET_BUCKET_KEY_RING
      - MONGODB_URL_PROTOCOL
      - MONGODB_USER
      - MONGODB_HOST
      - MONGODB_DATABASE

networks:
  default:
    external:
      name: cloudbuild
