version: "2"
services:
  staged:
    image: us.gcr.io/smn-core-staging/service.view-store.dashboard
    container_name: staged
    ports:
      - "50051:50051"

networks:
  default:
    external:
      name: cloudbuild
