version: "3"
services:
  staged:
    image: us.gcr.io/${_GCP_PROJECT}-staging/${_DOMAIN}.view-store.${_ID}
    container_name: staged
    ports:
      - "50051:50051"

networks:
  default:
    external:
      name: cloudbuild
